master/master.cfg

The octave-stable builder seems to have problems updating the gnulib repository. The log shows that it tries to fetch from a "stable" branch (which doesn't exist in the upstream repository).
Maybe specifying the branch explicitly will help with this build step.
Side note: Why is this build step even necessary? Won't the bootstrap script in Octave's hg repository do that automatically?
I'm still learning how to interact with github. Please, let me know if this is not the way to propose changes.

master.cfg: Specify branch for gnulib git repository

---

master/defaults/master.cfg

Add "--enable-ccache" to the configure flags of the MXE Octave builders.

Update master.cfg: Use ccache if available on worker

---

.github/workflows/check.yaml

Actions requiring Node.js 12 are deprecated.
See: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

check.yaml: Update to pat-s/always-upload-cache@v3.

---

.github/workflows/check.yaml

The `fits` package has been removed from MXE Octave here:
https://hg.octave.org/mxe-octave/rev/96ea694f0d48
No longer include it in the tested packages.

check.yaml (test packages): Remove package that has been removed from MXE Octave.

---

.github/workflows/check.yaml

Use the action that is maintained by GitHub now that it allows saving the cache on error.

check.yaml: Revert to "official" cache action.

---

.github/workflows/check.yaml

The opengl32.dll from mesa3d (llvmpipe) that is included in Octave for Windows leads to frequent crashes when trying to print (e.g., to a file or pipe). Use the OpenGL drivers installed on the system instead (even if they lead to test failures on the headless runners).

check.yaml: Use system OpenGL drivers on 32-bit.

---

.github/workflows/check.yaml

The buildbot worker on jwe's machine takes longer to build all variants than the previously used machine. Schedule the check at a later time of day to give more time for all variants to complete building and uploading.

check.yaml: Schedule check at a later time of day.

---

.github/workflows/check.yaml

`octave-launch.exe` now returns the exit code from the Octave process.
See: https://hg.octave.org/mxe-octave/rev/392c5255d044
Don't terminate testing the installed Octave packages on an error. But display a message and continue with the remaining packages.

check.yaml: React on error code returned by octave-launch.exe

---

.github/workflows/check.yaml

The launcher no longer attaches to a CLI unless it already knows that no GUI will be used.
Add the `--no-gui` flag (also for this headless runner).

check.yaml: Tell the launcher that we won't use a GUI.

---

.github/workflows/check.yaml

Octave for Windows 32-bit is no longer supported. The Octave project no longer distributes updated binaries for that target. (And the checks are already failing since some time.)
So, just stop testing them.

GitHub-CI: No longer check the 32-bit Windows package

---

master/defaults/master.cfg

Octave for Windows 32-bit is no longer supported. The Octave project no longer distributes updated binaries for that target. (And the checks are already failing since some time.)
So, stop building them in CI.
This is a companion PR to #25 (and should be merged after the other PR).

Skip building MXE Octave for Windows 32-bit

---

master/defaults/master.cfg

This change includes the content of the folder of unsuccessful build attempts (i.e., the `tmp-*` folder(s)) in the archive with the log files.
That might help to debug build issues if the content of the log file alone isn't helpful enough.

Include tmp-* folders in log file archive.

---

.github/workflows/build.yml
.github/workflows/check.yaml

.github/workflows/build.yaml, check.yaml: GitHub-hosted runners are transitioning from Node.js 16 to Node.js 20. Update to the latest versions of actions to prepare for that change.
See: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

Update GitHub actions to newer versions.

---

.github/workflows/check.yaml

See: https://hg.octave.org/mxe-octave/rev/5caa20111eb1

GitHub-CI: Package "tisean" is no longer built by MXE Octave.

---

.github/workflows/check.yaml

The image-acquisition package has been added to MXE Octave: https://hg.octave.org/mxe-octave/rev/42e2f4163413
Run its tests as part of the CI.

GitHub-CI: Add image-acquisition to list of Octave packages

---

.github/workflows/check.yaml

The parallel package has been added to MXE Octave: https://hg.octave.org/mxe-octave/rev/e3c37060acde
Run its tests as part of the CI.

GitHub-CI: Add parallel to list of Octave packages

---

.github/workflows/check.yaml

The fl-core package has been re-enabled in MXE Octave: https://hg.octave.org/mxe-octave/rev/b009ee00e657
Run its tests as part of the CI.

GitHub-CI: Add fl-core to list of Octave packages

---

master/defaults/master.cfg

MXE Octave doesn't (currently?) support building with parallel `make` initially. However, once Octave has been (cross-)built, building multiple packages in parallel works fine. And it is more efficient to do so, e.g., because some parts of the build steps of any of the built packages (like running a configure script) cannot be parallelized. Building multiple packages in parallel allows using more CPU threads at the same time in these cases.
To allow that, invoke `make` twice: First, to build Octave (without parallel `make`). And then again if the previous invocation was successful, to build the remaining tools and packages (with four parallel `make` processes).
That should be the equivalent of running the following command locally: 
`make JOBS=8 && make -j4 JOBS=2 all 7z-dist zip-dist …

Build packages in parallel.

---

master/defaults/master.cfg

The buildbots are failing after #35 with errors like the following:
* builtins.NameError: name 'SUCCESS' is not defined
* builtins.NameError: name 'SKIPPED' is not defined
That might be because these constants need to be fully qualified. 
Add the full namespace where these constants are used.
@siko1056: This is still untested. But maybe it helps to fix the changes from #35. Should we revert #35? Or attempt with this change?

Attempt to fix errors about undefined names.

---

master/defaults/app/octave_download_app.html
master/defaults/app/octave_download_app.py
master/defaults/master.cfg

The anonymous access over HTTPS to the Mercurial repository on Savannah is getting more and more unreliable. (That is possibly because crawlers for LLMs are hammering that server with a torrent of requests.)
Attempt to pull the repository from the mirror of the Octave repository on GitHub instead.
That way, we only rely on the synchronization from the Mercurial repository on Savannah to the GitHub mirror. But we don't rely on the Mercurial repository on Savannah to be available each time a build starts or the buildbot scheduler checks for updates.
The MXE Octave repository (on the Digital Ocean server) is still responsive most of the time. (Maybe, the crawlers didn't find it yet.) And we don't have a mirror for that (yet?). So, keep pulling the Mercurial repository for it.
These might …

Pull from Octave mirror on GitHub.
